name: Lint

on:
  workflow_call:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  RUNNER_TOOL_CACHE: /toolcache

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup repository
        uses: ./.github/actions/setup-repository

      - name: Lint code
        uses: ./.github/actions/lint-code
