name: Build next branch

on:
  push:
    branches:
      - next

jobs:
  lint:
    uses: ./.github/workflows/_lint.yaml

  test:
    uses: ./.github/workflows/_test.yaml

  sonar:
    needs: [test]
    uses: ./.github/workflows/_sonar.yaml
    secrets: inherit

  release:
    name: Release & Publish
    needs: [lint, sonar]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup repository
        uses: ./.github/actions/setup-repository

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN_READ }}
        shell: bash
        run: just release

      - name: Publish artifacts
        shell: pwsh
        run: just dotnet::publish xsdk.sln ${{ secrets.NUGET_API_KEY }}
