# Configuration file for MegaLinter
#
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

# Generic Settings
CLEAR_REPORT_FOLDER: true
FLAVOR_SUGGESTIONS: false
IGNORE_GITIGNORED_FILES: true
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_DEFAULT_STYLE: markdownlint
TYPESCRIPT_DEFAULT_STYLE: prettier
SHOW_ELAPSED_TIME: true
DISABLE_ERRORS: false
PARALLEL: true
PRINT_ALPACA: false
# Reporter Config
CONSOLE_REPORTER: true
TEXT_REPORTER: true
EMAIL_REPORTER: false
CONFIG_REPORTER: false
GITHUB_COMMENT_REPORTER: false
GITHUB_STATUS_REPORTER: false
GITLAB_COMMENT_REPORTER: false
AZURE_COMMENT_REPORTER: false
BITBUCKET_COMMENT_REPORTER: false
SARIF_REPORTER: false
UPDATED_SOURCES_REPORTER: false
FILEIO_REPORTER: false
TAP_REPORTER: false
# Exclude Config
EXCLUDED_DIRECTORIES:
  - .config
  - .devcontainer
  - .git
  - .github
  - .vs
  - dist
  - node_modules
ADDITIONAL_EXCLUDED_DIRECTORIES:
  - bin
  - obj
  - TestResults
  - megalinter-reports
# Language config
ENABLE:
  - CSHARP
  - CREDENTIALS
  - EDITORCONFIG
  - GIT
  - JSON
  - MARKDOWN
  - POWERSHELL
  - REPOSITORY
  - TYPESCRIPT
  - XML
  - YAML
# Linter config
ENABLE_LINTERS:
  - REPOSITORY_DEVSKIM
  - REPOSITORY_GITLEAKS
DISABLE_LINTERS:
  - REPOSITORY_CHECKOV
  - REPOSITORY_GRYPE
  - REPOSITORY_KICS
  - REPOSITORY_KINGFISHER
  - REPOSITORY_LS_LINT
  - REPOSITORY_SECRETLINT
  - REPOSITORY_TRIVY
  - REPOSITORY_TRIVY_SBOM
  - REPOSITORY_TRUFFLEHOG
  - REPOSITORY_SYFT
  - CSHARP_ROSLYNATOR
  - CSHARP_DOTNET_FORMAT
  - CSHARP_CSHARPIER
# Specific linter configs
EDITORCONFIG_EDITORCONFIG_CHECKER_DISABLE_ERRORS: true
EDITORCONFIG_EDITORCONFIG_CHECKER_FILTER_REGEX_EXCLUDE: (packages.lock.json|package-lock.json|yarn.lock|pnpm-lock.yaml)
JSON_JSONLINT_ARGUMENTS: --comments
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml|package-lock.json|yarn.lock|packages.lock.json)
YAML_V8R_FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml|package-lock.json|yarn.lock|packages.lock.json)
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: (pnpm-lock.yaml|package-lock.json|yarn.lock|packages.lock.json)
