name: 'Source code scanner'
description: 'Scans source code with Sonar Qube'
inputs:
  sast_host_url:
    description: 'Host of Static Source Code Analyzer'
    required: true
  sast_token:
    description: 'Token to login to SonarQube'
    required: true


runs:
  using: "composite"
  steps:
    - name: Scan Code
      shell: bash
      run: cdxgen --recurse --fail-on-error --output ./bom.json

    - uses: DependencyTrack/gh-upload-sbom@v3.1.0
      with:
        serverHostname: ${{ inputs.sast_host_url }}
        apiKey: ${{ inputs.sast_token }}
        projectName: ${{ github.repository }}
        projectVersion: ${{ github.ref_name }}
        bomFilename: "./bom.json"
        autoCreate: true
