name: Create release
description: Release the source code

runs:
  using: composite
  steps:
    - name: Release the code
      env:
          GITEA_TOKEN: ${{ github.token }}
          GH_TOKEN: ${{ github.token }}
      shell: bash
      run: npx semantic-release
