/*
 * Copyright 2026 Roland Breitschaft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using xSdk.Extensions.Plugin;
using xSdk.Extensions.Variable.Attributes;

namespace xSdk.Extensions.DataProtection;

[VariablePrefix("encryption")]
public sealed class DataProtectionPluginOptions : PluginOptions
{
    [Variable(
        name: Definitions.Discriminator.Name,
        template: Definitions.Discriminator.Template,
        helpText: Definitions.Discriminator.HelpText
    )]
    public string? Discriminator
    {
        get => this.ReadValue<string>(Definitions.Discriminator.Name);
        set => this.SetValue(Definitions.Discriminator.Name, value);
    }

    [Variable(
        name: Definitions.KeyLifetime.Name,
        template: Definitions.KeyLifetime.Template,
        helpText: Definitions.KeyLifetime.HelpText
    )]
    public string? KeyLifetime
    {
        get => this.ReadValue<string>(Definitions.KeyLifetime.Name);
        set => this.SetValue(Definitions.KeyLifetime.Name, value);
    }

    public static class Definitions
    {
        public static class Discriminator
        {
            public const string Name = nameof(Discriminator);
            public const string Template = "--discriminator <{Name}>";

            public const string HelpText =
                "An identifier that uniquely discriminates this application from all other applications on the machine. " +
                "The discriminator value is implicitly included in all protected payloads generated by the data protection system " +
                "to isolate multiple logical applications that all happen to be using the same key material. " +
                "If two different applications need to share protected payloads, they should ensure that this property " +
                "is set to the same value across both applications.";
        }

        public static class KeyLifetime
        {
            public const string Name = nameof(KeyLifetime);
            public const string Template = "--lifetime <lifetime>";
            public const string HelpText = "Sets the default lifetime of keys created by the data protection system.";
        }
    }
}
