name: Setup workflows
description: Prepares the workflow for running

runs:
  using: composite
  steps:
    - name: Setup just
      uses: extractions/setup-just@v3

    - name: Setup Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Install dependencies
      shell: bash
      run: just install
