name: Publish NuGet package
description: Publish the created NuGet packages to Artifactory
inputs:
  nuget_host_url:
    description: Host of Nuget Artifactory
    required: true
  nuget_token:
    description: Token to publish to Artifactory
    required: true

runs:
  using: composite
  steps:
    - name: Publish artifacts
      shell: pwsh
      run: |
        just publish-nuget
        dotnet nuget push --skip-duplicate --api-key "${{ inputs.nuget_token }}" --source "${{ inputs.nuget_host_url }}" ./dist/nuget/*.nupkg
