services:
  neo4j:
    image: neo4j:latest
    volumes:
        - ./logs:/logs
        - ./config:/config
        - ./data:/data
        - ./plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/your_password
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always
