name: Build feature branch

on:
  push:
    branches:
      - feature-*

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  RUNNER_TOOL_CACHE: /toolcache

jobs:
  build:
    name: Build feature branch
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup repository
        uses: ./.github/actions/setup-repository

      - name: Scan for code issues
        if: success()
        uses: ./.github/actions/code-scan
        with:
          sonar_token: ${{ secrets.SONAR_TOKEN }}
