name: 'Code Consistency Scan for .NET'

on:
  workflow_dispatch:
  pull_request:
    branches: [main, next]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  megalinter:
    name: 'Scan Code Consistency'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Wichtig für Mega-Linter, um Differenzen zu erkennen

      - name: Run Mega-Linter
        uses: oxsecurity/megalinter/flavors/dotnetweb@0e3ce9b9c8c10effb9b269509cc47ca17cae31c7
        env:
          MEGALINTER_CONFIG: .mega-linter.yml
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Wir erzwingen hier den Status-Reporter für GitHub,
          # damit der PR-Check grün/rot wird, auch wenn es in der Datei auf false steht.
          GITHUB_STATUS_REPORTER: true
          # Nur geänderte Dateien im PR scannen (spart extrem viel Zeit)
          VALIDATE_ALL_CODEBASE: false
