name: Release

on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.gitignore'
      - '.just/**'
      - '.vscode/**'
      - 'demos/**'
      - 'docs/**'
      - 'tools/**'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run (Do not create an actual release)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Setup just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b

      - name: Install Dependencies
        run: just install

      - name: Validate Release Config
        run: |
          if [ ! -f release.config.js ]; then
            echo "❌ Error: release.config.js not found!"
            exit 1
          fi
          echo "✅ Release config found. Ready to proceed."

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just release ${{ github.event.inputs.dry_run == 'true' || 'false' }}

      - name: Publish
        if: github.event.inputs.dry_run != 'true'
        shell: pwsh
        env:
          token: ${{ secrets.NUGET_API_KEY }}
          nuget_host_url: 'https://api.nuget.org/v3/index.json'
          dist_dir: 'dist'
        run: |
          just dotnet::publish xsdk.sln
          dotnet nuget push --skip-duplicate --api-key "${token}" --source "${nuget_host_url}" "dist/nuget/*.nupkg"
