name: Release

on:
  push:
    branches:
      - main
      - next
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '.gitignore'
      - '.just/**'
      - '.vscode/**'
      - 'demos/**'
      - 'docs/**'
      - 'tools/**'
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry Run (Do not create an actual release)'
        required: false
        type: boolean
        default: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup repository
        uses: ./.github/actions/setup-repository

      - name: Validate Release Config
        run: |
          if [ ! -f release.config.js ]; then
            echo "❌ Error: release.config.js not found!"
            exit 1
          fi
          echo "✅ Release config found. Ready to proceed."

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: just repository::release ${{ github.event.inputs.dry_run || 'false' }}

      - name: Publish
        if: github.event.inputs.dry_run != 'true'
        shell: pwsh
        env:
          token: ${{ secrets.NUGET_API_KEY }}
          nuget_host_url: 'https://api.nuget.org/v3/index.json'
          dist_dir: 'dist'
        run: |
          just dotnet::publish xsdk.sln
          dotnet nuget push --skip-duplicate --api-key "$env:token" --source "$env:nuget_host_url" "dist/nuget/*.nupkg"
